// SPDX-License-Identifier: AGPL-3.0-or-later
// THE SERVICE WORKER, WRITTEN AFTER THE BUILD BECAUSE ONLY THE BUILD KNOWS THE FILE NAMES.
//
// Vite hashes every asset, so a precache list cannot be checked in - it would be a list of names from the
// last build somebody remembered to update, which is the shape of a cache that serves a page and a script
// from different releases.
//
// ⚠️ IT IMPORTS THE RULES RATHER THAN RESTATING THEM. Node 24 strips TypeScript natively, so this reads
// `app/js/pwa/precache.ts` - the same module `tests/precache.node.test.ts` measures. A build script with
// its own copy of "exclude the wasm" is a second source for the one decision this feature has to get
// right, and the copy is the one that runs.
//
// ⚠️ AND IT REFUSES TO WRITE A BAD WORKER. Over budget, or a build with no document or no script, exits
// non-zero: a service worker that caches nothing installs happily and reports success, and the failure
// surfaces as "the game does not work on the school's wifi" three weeks later.
import { readdir, stat, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative, sep } from 'node:path';
import { precachePlan, PRECACHE_BUDGET_BYTES } from '../app/js/pwa/precache.ts';

const DIST = join(import.meta.dirname, '..', 'dist');

/** Every file under `dist`, as the plan wants them: forward slashes, relative, no leading slash. */
async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await walk(full)));
      continue;
    }
    const { size } = await stat(full);
    out.push({ path: relative(DIST, full).split(sep).join('/'), bytes: size });
  }
  return out;
}

const files = await walk(DIST);
const plan = precachePlan(files);

for (const problem of plan.problems) console.error(`✗ precache: ${problem}`);
if (plan.problems.length) process.exit(1);

const kib = (n) => `${(n / 1024).toFixed(0)} KiB`;
if (plan.overBudget) {
  console.error(`✗ precache: ${kib(plan.bytes)} exceeds the budget of ${kib(PRECACHE_BUDGET_BYTES)}.`);
  console.error('  What it would store:');
  for (const path of plan.precache) console.error(`    ${path}`);
  process.exit(1);
}

// ⚠️ THE CACHE NAME IS A HASH OF WHAT IS IN IT, not a version somebody bumps. A name bumped by hand is a
// name somebody forgets, and the symptom is a child served last week's script with this week's HTML -
// which looks like the game being broken rather than like a stale cache.
const version = createHash('sha256').update(plan.precache.join('\n')).digest('hex').slice(0, 12);

const worker = `// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED BY scripts/build-sw.mjs - do not edit; edit the script and the rules it imports.
//
// Pillar 8: a school gets the game once and then does not need the network. What is stored at install is
// what the page ACTUALLY fetches - measured, not guessed - which is ${kib(plan.bytes)} rather than the
// 16 MB the whole build weighs. The difference is one file: the speech runtime this game never calls.
const CACHE = 'soccer-${version}';
const PRECACHE = ${JSON.stringify(plan.precache.map((p) => './' + p), null, 2)};

self.addEventListener('install', (event) => {
  // \`skipWaiting\` because a child who reloads to fix something must GET the fix, rather than the old
  // worker holding the page until every tab is closed.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // A navigation offline has to land on the document we stored, whatever path was typed.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('./index.html').then((r) => r || Response.error())),
    );
    return;
  }

  // Cache first, then the network - and what the network gives back is kept. That is how a typeface a
  // child picks on Monday is still there on Tuesday with the wifi down, without every machine paying for
  // thirty-four of them on the first visit.
  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).then((response) => {
        if (!response.ok || response.type === 'opaque') return response;
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put(request, copy));
        return response;
      });
    }),
  );
});
`;

await writeFile(join(DIST, 'sw.js'), worker, 'utf8');
console.log(`✓ sw.js: ${plan.precache.length} files, ${kib(plan.bytes)} of ${kib(PRECACHE_BUDGET_BYTES)}.`);
console.log(`  left out: ${plan.skipped.length} files, fetched on demand.`);
